import { getAllPosts, getPostsForTopPage } from "@/lib/notionAPI";
import localFont from "next/font/local";
import Image from "next/image";
import Head from "next/head";
import { SinglePost } from "@/components/Post/SinglePost";
import { GetStaticPaths, GetStaticProps } from "next";

export const getStaticPaths: GetStaticPaths = async () => {
    return {
        paths: [{ params: { page: "1" } }, { params: { page: "2" } }],
        fallback: "blocking",
    };
};

export const getStaticProps: GetStaticProps = async () => {
    const displayPosts = await getPostsForTopPage(4);

    return {
        props: {
            displayPosts,
        },
        revalidate: 60 * 60 * 6,
    };
};

interface Post {
    title: string;
    description: string;
    date: string;
    tags: string[];
    slug: string;
}

interface PageListProps {
    displayPosts: Post[];
}

const PageList = ({ displayPosts }: PageListProps) => {
    return (
        <div className="container h-full w-full mx-auto">
            <Head>
                <title>Errorda2</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container w-full mt-16">
                <h1 className="text-5x1 font-medium text-center mb-16">Errorda2</h1>
                {displayPosts.map(
                    (post: { title: string; description: string; date: string; tags: string[]; slug: string }) => (
                        <div className="mx-4">
                            <SinglePost
                                title={post.title}
                                description={post.description}
                                date={post.date}
                                tags={post.tags}
                                slug={post.slug}
                            />
                        </div>
                    ),
                )}
            </main>
        </div>
    );
};

export default PageList;
