import { getAllTags, getPostsForTopPage } from "@/lib/notionAPI";
import Head from "next/head";
import { SinglePost } from "@/components/Post/SinglePost";
import { GetStaticProps } from "next";
import Link from "next/link";
import Tag from "@/components/Tag/Tag";

export const getStaticProps: GetStaticProps = async () => {
    const displayPosts = await getPostsForTopPage(4);
    const allTags = await getAllTags();

    return {
        props: {
            displayPosts,
            allTags,
        },
        revalidate: 60 * 60 * 6,
    };
};

interface Post {
    id: string;
    title: string;
    description: string;
    date: string;
    tags: string[];
    slug: string;
}

export default function Home({ displayPosts, allTags }: { displayPosts: Post[]; allTags: string[] }) {
    return (
        <div className="container h-full w-full mx-auto">
            <Head>
                <title>Errorda2</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container w-full mt-16">
                <h1 className="text-5x1 font-medium text-center mb-16">Errorda2</h1>
                {displayPosts.map(
                    (post: {
                        id: string;
                        title: string;
                        description: string;
                        date: string;
                        tags: string[];
                        slug: string;
                    }) => (
                        <div className="mx-4" key={post.id}>
                            <SinglePost
                                title={post.title}
                                description={post.description}
                                date={post.date}
                                tags={post.tags}
                                slug={post.slug}
                                isPaginationPage={false}
                            />
                        </div>
                    ),
                )}
                <Link href="/posts/page/1" className="mb-6 lg:w-1/2 mx-auto px-5 block text-right">
                    ...もっと見る
                </Link>
                <Tag tags={allTags} />
            </main>
        </div>
    );
}
