import { getAllPosts } from "@/lib/notionAPI";
import localFont from "next/font/local";
import Image from "next/image";

export const getStaticProps = async () => {
    const allPosts = await getAllPosts();

    return {
        props: {
            allPosts,
        },
        revalidate: 60 * 60 * 6,
    };
};

export default function Home({ allPosts }) {
    console.log(allPosts);
    return (
        <div>
            <main>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </main>
        </div>
    );
}
