import {
    getAllPosts,
    getNumberOfPages,
    getPostsByPage,
    getPostsByTagAndPage,
    getPostsForTopPage,
    getNumberOfPagesByTag,
    getAllTags,
} from "@/lib/notionAPI";
import localFont from "next/font/local";
import Image from "next/image";
import Head from "next/head";
import { SinglePost } from "@/components/Post/SinglePost";
import { GetStaticPaths, GetStaticProps } from "next";
import Pagination from "@/components/Pagination/Pagination";

export const getStaticPaths: GetStaticPaths = async () => {
    const allTags = await getAllTags();
    let params: { params: { tag: string; page: string } }[] = [];

    await Promise.all(
        allTags.map((tag: string) => {
            return getNumberOfPagesByTag(tag).then((numberOfPagesByTag: number) => {
                for (let i = 1; i <= numberOfPagesByTag; i++) {
                    params.push({ params: { tag: tag, page: i.toString() } });
                }
            });
        }),
    );

    return {
        paths: params,
        fallback: "blocking",
    };
};

export const getStaticProps: GetStaticProps = async (context) => {
    const currentPage: string = context.params?.page?.toString() || "";
    const currentTag: string = context.params?.tag?.toString() || "";

    const upperCaseCurrentTag = currentTag.charAt(0).toUpperCase() + currentTag.slice(1);

    const posts = await getPostsByTagAndPage(upperCaseCurrentTag, parseInt(currentPage, 10));

    const numberOfPagesByTag = await getNumberOfPagesByTag(upperCaseCurrentTag);
    const allTags = await getAllTags();

    return {
        props: {
            posts,
            numberOfPagesByTag,
            currentTag,
        },
        revalidate: 60 * 60 * 6,
    };
};

interface Post {
    id: string;
    title: string;
    description: string;
    date: string;
    tags: string[];
    slug: string;
}

interface PageListProps {
    posts: Post[];
    numberOfPage: number;
    numberOfPagesByTag: number;
    currentTag: string;
}

const TagPageList = ({ numberOfPagesByTag, posts, currentTag }: PageListProps) => {
    return (
        <div className="container h-full w-full mx-auto">
            <Head>
                <title>Errorda2</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container w-full mt-16">
                <h1 className="text-5x1 font-medium text-center mb-16">Errorda2</h1>
                <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
                    {posts.map((post: Post) => (
                        <div key={post.id}>
                            <SinglePost
                                title={post.title}
                                description={post.description}
                                date={post.date}
                                tags={post.tags}
                                slug={post.slug}
                                isPaginationPage={true}
                            />
                        </div>
                    ))}
                </section>
                <Pagination numberOfPage={numberOfPagesByTag} tag={currentTag} />
            </main>
        </div>
    );
};

export default TagPageList;
